---
  name: Release
  
  on:
    workflow_dispatch:
    push:
      tags:
        - "v*"
  
  jobs:
    release:
      name: "Release"
  
      permissions:
        contents: write
  
      runs-on: "ubuntu-latest"
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
  
        - uses: pnpm/action-setup@v4
          name: Install pnpm
          id: pnpm-install
          with:
            version: 10
            run_install: true
  
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: pnpm
 
        - name: Typecheck
          run: pnpm typecheck
  
        - name: Check
          run: pnpm check

        - name: Build
          run: |
            pnpm build
  
        - name: Create Release with Changelog
          run: pnpx changelogithub
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
